### ISSUE TITLE
Export alfredsnippets into other format?

### ISSUE THREAD

**Issue by tigecyclindamycin** [AndiH/alfred-snippets#1]
Hi there, thanks for the helpful guide with instructions for exporting .csv into .alfredsnippets. Unfortunately, I'm actually looking for a solution for the reverse, as I want to move my snippets to a better text expansion service. May I ask if it's possible to export .alfredsnippets into .csv? How may I go about it?

**Comment by AndiH** [comment]
I've not touched this project for 5 years, so I can't really help with that, unfortunately.

But, as I look through the script which I wrote 5 years ago, it seems like unzipping the Alfred snippet and then _converting_ the resulting JSON into CSV should do the trick. Have a look at the conversion Python script in this repo. You should be able to whip up something reverse!
